services:
  back_end:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:${PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
    extra_hosts:
      - host.docker.internal:host-gateway
  migrator:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    command: ["node", "./migrate.mjs"]
    env_file:
      - path: ./.env
        required: true
    depends_on:
      back_end:
        condition: service_healthy
    restart: "no"
